// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ExamType string

const (
	ExamTypeFINALEXAM ExamType = "FINAL_EXAM"
	ExamTypeCAT       ExamType = "CAT"
)

func (e *ExamType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExamType(s)
	case string:
		*e = ExamType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExamType: %T", src)
	}
	return nil
}

type NullExamType struct {
	ExamType ExamType
	Valid    bool // Valid is true if ExamType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExamType) Scan(value interface{}) error {
	if value == nil {
		ns.ExamType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExamType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExamType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExamType), nil
}

type MaterialType string

const (
	MaterialTypeFILE        MaterialType = "FILE"
	MaterialTypeURL         MaterialType = "URL"
	MaterialTypeCODESNIPPET MaterialType = "CODE_SNIPPET"
	MaterialTypeGOOGLEBOOK  MaterialType = "GOOGLE_BOOK"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType
	Valid        bool // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

type NotificationType string

const (
	NotificationTypeSYSTEMUPDATE        NotificationType = "SYSTEM_UPDATE"
	NotificationTypeANNOUNCEMENT        NotificationType = "ANNOUNCEMENT"
	NotificationTypeMESSAGE             NotificationType = "MESSAGE"
	NotificationTypeASSIGNMENTSUBMITTED NotificationType = "ASSIGNMENT_SUBMITTED"
	NotificationTypeASSIGNMENTGRADED    NotificationType = "ASSIGNMENT_GRADED"
	NotificationTypeSUBMISSIONFAILED    NotificationType = "SUBMISSION_FAILED"
	NotificationTypeNEWEVENT            NotificationType = "NEW_EVENT"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type OnlineExamStatus string

const (
	OnlineExamStatusPENDINGAPPROVAL OnlineExamStatus = "PENDING_APPROVAL"
	OnlineExamStatusAPPROVED        OnlineExamStatus = "APPROVED"
	OnlineExamStatusREJECTED        OnlineExamStatus = "REJECTED"
	OnlineExamStatusNOTAPPLICABLE   OnlineExamStatus = "NOT_APPLICABLE"
)

func (e *OnlineExamStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnlineExamStatus(s)
	case string:
		*e = OnlineExamStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OnlineExamStatus: %T", src)
	}
	return nil
}

type NullOnlineExamStatus struct {
	OnlineExamStatus OnlineExamStatus
	Valid            bool // Valid is true if OnlineExamStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnlineExamStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OnlineExamStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnlineExamStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnlineExamStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnlineExamStatus), nil
}

type RiskLevel string

const (
	RiskLevelLow    RiskLevel = "Low"
	RiskLevelMedium RiskLevel = "Medium"
	RiskLevelHigh   RiskLevel = "High"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel
	Valid     bool // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type RoomType string

const (
	RoomTypeClassroom    RoomType = "Classroom"
	RoomTypeLab          RoomType = "Lab"
	RoomTypeLectureHall  RoomType = "LectureHall"
	RoomTypeDepartmental RoomType = "Departmental"
	RoomTypeOther        RoomType = "Other"
)

func (e *RoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomType(s)
	case string:
		*e = RoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomType: %T", src)
	}
	return nil
}

type NullRoomType struct {
	RoomType RoomType
	Valid    bool // Valid is true if RoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomType), nil
}

type AcademicClass struct {
	ClassID            uuid.UUID
	SchoolID           uuid.UUID
	CourseID           uuid.UUID
	TeacherID          uuid.UUID
	ClassName          string
	AcademicYear       string
	Semester           sql.NullString
	StartDate          sql.NullTime
	EndDate            sql.NullTime
	AttendancePriority string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
}

type Application struct {
	ApplicationID           uuid.UUID
	SchoolID                uuid.NullUUID
	ApplicantUserID         uuid.UUID
	ApplicantFirstName      string
	ApplicantLastName       string
	ApplicantEmail          string
	SchoolNameAtApplication string
	DesiredRole             string
	Status                  string
	Notes                   sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type Asset struct {
	AssetID          uuid.UUID
	SchoolID         uuid.UUID
	AssetName        string
	SerialNumber     sql.NullString
	Category         sql.NullString
	PurchaseDate     sql.NullTime
	Value            sql.NullString
	Status           string
	AssignedToUserID uuid.NullUUID
	Location         sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Assignment struct {
	AssignmentID    uuid.UUID
	SchoolID        uuid.UUID
	ClassID         uuid.UUID
	TeacherID       uuid.UUID
	Title           string
	Description     sql.NullString
	DueDate         sql.NullTime
	MaxScore        string
	AssignmentType  string
	FileUrl         sql.NullString
	QuizID          uuid.NullUUID
	GradeCategoryID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AttendanceRecord struct {
	AttendanceID   uuid.UUID
	SchoolID       uuid.UUID
	StudentID      uuid.UUID
	ClassID        uuid.UUID
	AttendanceDate time.Time
	Status         string
	Notes          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AuditLog struct {
	LogID        uuid.UUID
	SchoolID     uuid.NullUUID
	UserID       uuid.NullUUID
	Action       string
	EntityType   string
	EntityID     uuid.NullUUID
	OldValue     pqtype.NullRawMessage
	NewValue     pqtype.NullRawMessage
	IpAddress    sql.NullString
	UserAgent    sql.NullString
	LoggedAt     time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	SearchVector interface{}
}

type Badge struct {
	BadgeID     uuid.UUID
	SchoolID    uuid.UUID
	BadgeName   string
	Description sql.NullString
	IconUrl     sql.NullString
	Criteria    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BadgeCourse struct {
	BadgeCourseID  uuid.UUID
	BadgeID        uuid.UUID
	SchoolID       uuid.UUID
	TeacherID      uuid.UUID
	Title          string
	Description    sql.NullString
	IsFree         bool
	CompletionType string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type BillingContact struct {
	BillingContactID uuid.UUID
	SchoolID         uuid.UUID
	Name             string
	Email            string
	PhoneNumber      sql.NullString
	Role             sql.NullString
	IsPrimary        bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type BookCopy struct {
	CopyID    uuid.UUID
	BookID    uuid.UUID
	Barcode   string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChatMessage struct {
	MessageID     uuid.UUID
	SchoolID      uuid.UUID
	ChatRoomID    uuid.UUID
	SenderID      uuid.UUID
	MessageText   string
	AttachmentUrl sql.NullString
	SentAt        time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ChatParticipant struct {
	ParticipantID   uuid.UUID
	SchoolID        uuid.UUID
	ChatRoomID      uuid.UUID
	UserID          uuid.UUID
	JoinedAt        time.Time
	LeftAt          sql.NullTime
	Status          string
	InvitedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ChatRoom struct {
	ChatRoomID        uuid.UUID
	SchoolID          uuid.UUID
	ChatName          string
	ChatType          string
	Description       sql.NullString
	IsActive          bool
	CreatedByUserID   uuid.NullUUID
	AssociatedClassID uuid.NullUUID
	AllowedFileTypes  []string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ClassRepresentative struct {
	ClassRepID                   uuid.UUID
	StudentUserID                uuid.UUID
	AcademicClassID              uuid.UUID
	CanCommunicateTeacher        bool
	CanCommunicateDepartmentHead bool
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	DeletedAt                    sql.NullTime
}

type ClinicVisit struct {
	VisitID   uuid.UUID
	SchoolID  uuid.UUID
	StudentID uuid.UUID
	NurseID   uuid.NullUUID
	VisitDate time.Time
	Symptoms  sql.NullString
	Diagnosis sql.NullString
	Treatment sql.NullString
	Notes     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Course struct {
	CourseID               uuid.UUID
	SchoolID               uuid.UUID
	CourseCode             string
	CourseName             string
	Description            sql.NullString
	IsShortCourse          bool
	Price                  sql.NullString
	IsGradedIndependently  bool
	RequiresAllUnitsPassed bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              sql.NullTime
}

type CourseSubject struct {
	CourseID  uuid.UUID
	SubjectID uuid.UUID
}

type Department struct {
	DepartmentID             uuid.UUID
	SchoolID                 uuid.UUID
	DepartmentName           string
	HeadOfDepartmentID       uuid.NullUUID
	DeputyHeadOfDepartmentID uuid.NullUUID
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                sql.NullTime
}

type DepartmentSubject struct {
	DepartmentID uuid.UUID
	SubjectID    uuid.UUID
}

type Enrollment struct {
	EnrollmentID   uuid.UUID
	SchoolID       uuid.UUID
	StudentID      uuid.UUID
	ClassID        uuid.UUID
	EnrollmentDate time.Time
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Event struct {
	EventID     uuid.UUID
	SchoolID    uuid.UUID
	Title       string
	Description sql.NullString
	EventDate   time.Time
	EndDate     sql.NullTime
	Location    sql.NullString
	EventType   string
	OrganizerID uuid.NullUUID
	IsPublic    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Exam struct {
	ExamID           uuid.UUID
	SchoolID         uuid.UUID
	SubjectID        uuid.UUID
	TeacherID        uuid.UUID
	Title            string
	Description      sql.NullString
	ExamType         ExamType
	IsOnline         bool
	OnlineExamStatus OnlineExamStatus
	ApprovedByUserID uuid.NullUUID
	DurationMinutes  sql.NullInt32
	StartTime        sql.NullTime
	EndTime          sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ExternalCertification struct {
	CertID          uuid.UUID
	StudentID       uuid.UUID
	Name            string
	Issuer          string
	CredentialID    sql.NullString
	VerificationUrl sql.NullString
	IssueDate       sql.NullTime
	ExpiryDate      sql.NullTime
	IsVerified      bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type FeeStructure struct {
	FeeStructureID uuid.UUID
	SchoolID       uuid.UUID
	FeeName        string
	Amount         string
	Currency       string
	AcademicYear   string
	Description    sql.NullString
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Feedback struct {
	FeedbackID   uuid.UUID
	SchoolID     uuid.NullUUID
	UserID       uuid.UUID
	Subject      sql.NullString
	Message      string
	Rating       sql.NullInt32
	FeedbackType string
	Status       string
	SubmittedAt  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Grade struct {
	GradeID        uuid.UUID
	SchoolID       uuid.UUID
	SubmissionID   uuid.UUID
	GradedByUserID uuid.NullUUID
	Score          string
	Feedback       sql.NullString
	GradedAt       time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GradeCategory struct {
	GradeCategoryID uuid.UUID
	GradingSystemID uuid.UUID
	Name            string
	Weight          string
}

type GradingSystem struct {
	GradingSystemID uuid.UUID
	SchoolID        uuid.UUID
	ClassID         uuid.UUID
	Name            string
	Description     sql.NullString
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Group struct {
	GroupID          uuid.UUID
	SchoolID         uuid.UUID
	Name             string
	Description      sql.NullString
	CreatedByUserID  uuid.UUID
	IsTeacherCreated bool
	MaxMembers       sql.NullInt32
	ChatRoomID       uuid.NullUUID
}

type GroupMember struct {
	GroupMemberID uuid.UUID
	GroupID       uuid.UUID
	UserID        uuid.UUID
	Status        string
}

type HealthRecord struct {
	RecordID          uuid.UUID
	StudentID         uuid.UUID
	BloodGroup        sql.NullString
	Allergies         sql.NullString
	MedicalConditions sql.NullString
	EmergencyNotes    sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type HostelAllocation struct {
	AllocationID uuid.UUID
	SchoolID     uuid.UUID
	UserID       uuid.UUID
	RoomID       uuid.UUID
	StartDate    time.Time
	EndDate      sql.NullTime
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type HostelBuilding struct {
	BuildingID   uuid.UUID
	SchoolID     uuid.UUID
	BuildingName string
	Type         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type HostelRoom struct {
	RoomID     uuid.UUID
	BuildingID uuid.UUID
	RoomNumber string
	Capacity   int32
	Floor      sql.NullInt32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type InventoryItem struct {
	ItemID       uuid.UUID
	SchoolID     uuid.UUID
	ItemName     string
	Category     sql.NullString
	Quantity     int32
	Unit         sql.NullString
	ReorderLevel sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type InventoryTransaction struct {
	TransactionID   uuid.UUID
	ItemID          uuid.UUID
	UserID          uuid.NullUUID
	TransactionType string
	Quantity        int32
	Notes           sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Invoice struct {
	InvoiceID      uuid.UUID
	SchoolID       uuid.UUID
	SubscriptionID uuid.NullUUID
	InvoiceNumber  string
	AmountDue      string
	AmountPaid     string
	Currency       string
	IssueDate      time.Time
	DueDate        time.Time
	Status         string
	Notes          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type LearningMaterial struct {
	MaterialID       uuid.UUID
	SchoolID         uuid.UUID
	UploadedByUserID uuid.UUID
	ClassID          uuid.NullUUID
	CourseID         uuid.NullUUID
	Title            string
	Description      sql.NullString
	FileUrl          sql.NullString
	Content          sql.NullString
	MaterialType     MaterialType
	ExternalData     pqtype.NullRawMessage
	UploadedAt       time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type LessonPlan struct {
	LessonPlanID        uuid.UUID
	SchoolID            uuid.UUID
	TeacherID           uuid.UUID
	ClassID             uuid.NullUUID
	SubjectID           uuid.NullUUID
	Title               string
	Topic               sql.NullString
	LessonNumber        sql.NullInt32
	Objectives          []string
	Content             sql.NullString
	AssessmentQuestions []string
	OnlineMeetingLink   sql.NullString
	DateCovered         sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
}

type LessonPlanLearningMaterial struct {
	LessonPlanID uuid.UUID
	MaterialID   uuid.UUID
}

type LibraryBook struct {
	BookID    uuid.UUID
	SchoolID  uuid.UUID
	Title     string
	Author    string
	Isbn      sql.NullString
	Publisher sql.NullString
	Category  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LibraryLoan struct {
	LoanID     uuid.UUID
	CopyID     uuid.UUID
	UserID     uuid.UUID
	BorrowedAt time.Time
	DueDate    time.Time
	ReturnedAt sql.NullTime
	Status     string
	FineAmount string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Meeting struct {
	MeetingID       uuid.UUID
	SchoolID        uuid.UUID
	Title           string
	Agenda          sql.NullString
	MeetingDate     time.Time
	DurationMinutes sql.NullInt32
	Location        sql.NullString
	MeetingType     string
	OrganizerID     uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type MeetingAttendee struct {
	MeetingID uuid.UUID
	UserID    uuid.UUID
	SchoolID  uuid.UUID
}

type Newsletter struct {
	NewsletterID  uuid.UUID
	Title         string
	Content       string
	SentAt        sql.NullTime
	SentByUserID  uuid.NullUUID
	TargetSchools pqtype.NullRawMessage
	Attachments   pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Notification struct {
	NotificationID   uuid.UUID
	SchoolID         uuid.UUID
	SenderID         uuid.NullUUID
	NotificationType NotificationType
	Title            string
	Message          string
	LinkUrl          sql.NullString
	EntityType       sql.NullString
	EntityID         sql.NullString
	SentAt           time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type NotificationRecipient struct {
	NotificationID uuid.UUID
	RecipientID    uuid.UUID
	IsRead         bool
	ReadAt         sql.NullTime
}

type OnlineClassSession struct {
	SessionID     uuid.UUID
	SchoolID      uuid.UUID
	ClassID       uuid.UUID
	TeacherID     uuid.UUID
	SessionTitle  string
	StartTime     time.Time
	EndTime       time.Time
	MeetingLink   string
	Description   sql.NullString
	RecordingLink sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Option struct {
	OptionID   uuid.UUID
	QuestionID uuid.UUID
	OptionText string
	IsCorrect  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ParentProfile struct {
	ParentProfileID       uuid.UUID
	UserID                uuid.UUID
	SchoolID              uuid.UUID
	HomeAddress           sql.NullString
	Occupation            sql.NullString
	EmergencyContactName  sql.NullString
	EmergencyContactPhone sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type ParentStudentRelationship struct {
	RelationshipID   uuid.UUID
	SchoolID         uuid.UUID
	ParentUserID     uuid.UUID
	StudentUserID    uuid.UUID
	RelationshipType string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Payment struct {
	PaymentID        uuid.UUID
	SchoolID         uuid.UUID
	StudentFeeID     uuid.UUID
	Amount           string
	PaymentDate      time.Time
	PaymentMethod    sql.NullString
	TransactionID    sql.NullString
	RecordedByUserID uuid.NullUUID
	Notes            sql.NullString
	ReceiptNumber    sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Question struct {
	QuestionID   uuid.UUID
	QuizID       uuid.NullUUID
	ExamID       uuid.NullUUID
	QuestionText string
	QuestionType string
	Order        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Quiz struct {
	QuizID          uuid.UUID
	AssignmentID    uuid.NullUUID
	SchoolID        uuid.UUID
	TeacherID       uuid.UUID
	SubjectID       uuid.NullUUID
	Title           string
	Description     sql.NullString
	QuizType        string
	DurationMinutes sql.NullInt32
	StartTime       sql.NullTime
	EndTime         sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type QuizAnswer struct {
	AnswerID          uuid.UUID
	QuizSubmissionID  uuid.UUID
	QuestionID        uuid.UUID
	StudentAnswerText sql.NullString
	SelectedOptionID  uuid.NullUUID
	IsCorrect         sql.NullBool
	DeletedAt         sql.NullTime
}

type QuizSubmission struct {
	SubmissionID uuid.UUID
	QuizID       uuid.UUID
	StudentID    uuid.UUID
	Score        sql.NullString
	SubmittedAt  time.Time
	Status       string
	DeletedAt    sql.NullTime
}

type Role struct {
	RoleID       uuid.UUID
	RoleName     string
	Description  sql.NullString
	IsSchoolRole bool
}

type Room struct {
	RoomID       uuid.UUID
	SchoolID     uuid.UUID
	RoomName     string
	Capacity     int32
	RoomType     RoomType
	DepartmentID uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type SaasCompanyProfile struct {
	SaasProfileID      uuid.UUID
	UserID             uuid.UUID
	JobTitle           string
	DepartmentNameText sql.NullString
	InternalEmployeeID sql.NullString
	HireDate           sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type School struct {
	SchoolID       uuid.UUID
	SchoolName     string
	Subdomain      sql.NullString
	Status         string
	SchoolInitial  sql.NullString
	Address        sql.NullString
	PhoneNumber    sql.NullString
	Email          sql.NullString
	LogoUrl        sql.NullString
	PrimaryColor   sql.NullString
	SecondaryColor sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type SchoolSetting struct {
	SettingID               uuid.UUID
	SchoolID                uuid.UUID
	BrandingLogoUrl         sql.NullString
	BrandingColors          json.RawMessage
	Timezone                string
	Preferences             json.RawMessage
	EmailTemplateConfigs    json.RawMessage
	PaymentProviders        pqtype.NullRawMessage
	EnableStrictProgression bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type SchoolStaffProfile struct {
	StaffProfileID     uuid.UUID
	UserID             uuid.UUID
	SchoolID           uuid.UUID
	EmployeeID         string
	DepartmentNameText sql.NullString
	Designation        string
	HireDate           sql.NullTime
	OfficeLocation     sql.NullString
	DepartmentID       uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SchoolSubscription struct {
	SubscriptionID  uuid.UUID
	SchoolID        uuid.UUID
	TierID          uuid.UUID
	StartDate       time.Time
	EndDate         time.Time
	Status          string
	BillingCycle    string
	LastPaymentDate sql.NullTime
	NextRenewalDate sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ShortCourseEnrollment struct {
	EnrollmentID         uuid.UUID
	SchoolID             uuid.UUID
	StudentID            uuid.UUID
	CourseID             uuid.UUID
	EnrollmentDate       time.Time
	Status               string
	AttemptType          string
	PreviousEnrollmentID uuid.NullUUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ShortCourseGrade struct {
	GradeID        uuid.UUID
	EnrollmentID   uuid.UUID
	CourseID       uuid.UUID
	StudentID      uuid.UUID
	Score          string
	Feedback       sql.NullString
	GradedByUserID uuid.NullUUID
	GradedAt       time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type StudentBadge struct {
	StudentBadgeID  uuid.UUID
	SchoolID        uuid.UUID
	StudentID       uuid.UUID
	BadgeID         uuid.UUID
	AwardedAt       time.Time
	AwardedByUserID uuid.NullUUID
	Notes           sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type StudentCourseProgress struct {
	ProgressID         uuid.UUID
	EnrollmentID       uuid.UUID
	ProgressPercentage string
	LastActivityAt     time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
}

type StudentFee struct {
	StudentFeeID   uuid.UUID
	SchoolID       uuid.UUID
	StudentID      uuid.UUID
	FeeStructureID uuid.UUID
	AmountDue      string
	AmountPaid     string
	DueDate        sql.NullTime
	Status         string
	Notes          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type StudentProfile struct {
	StudentProfileID  uuid.UUID
	UserID            uuid.UUID
	SchoolID          uuid.UUID
	EnrollmentNumber  string
	CurrentGradeLevel sql.NullString
	AdmissionDate     time.Time
	CurrentClassID    uuid.NullUUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type StudentRiskScore struct {
	RiskScoreID    uuid.UUID
	SchoolID       uuid.UUID
	StudentID      uuid.UUID
	AttendanceRate string
	AverageGrade   string
	RiskScore      int32
	RiskLevel      RiskLevel
	LastCalculated time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Subject struct {
	SubjectID            uuid.UUID
	SchoolID             uuid.UUID
	SubjectName          string
	Description          sql.NullString
	DoublePeriodRequired bool
	LabPeriodRequired    bool
	MaxOnlinePercentage  sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            sql.NullTime
}

type Submission struct {
	SubmissionID      uuid.UUID
	SchoolID          uuid.UUID
	StudentID         uuid.UUID
	AssignmentID      uuid.UUID
	SubmissionContent sql.NullString
	SubmittedAt       time.Time
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SubscriptionTier struct {
	TierID          uuid.UUID
	TierName        string
	Description     sql.NullString
	PricePerQuarter string
	Currency        string
	Features        pqtype.NullRawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TeacherAvailability struct {
	AvailabilityID uuid.UUID
	TeacherID      uuid.UUID
	DayOfWeek      int32
	StartTime      time.Time
	EndTime        time.Time
	IsRecurring    bool
	Notes          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type TeacherProfile struct {
	TeacherProfileID      uuid.UUID
	UserID                uuid.UUID
	SchoolID              uuid.UUID
	TeacherIDNumber       sql.NullString
	Specialization        sql.NullString
	Qualification         sql.NullString
	EmploymentStartDate   sql.NullTime
	IsClassTeacher        bool
	ClassTeacherOfClassID uuid.NullUUID
	DepartmentNameText    sql.NullString
	DepartmentID          uuid.NullUUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type TeacherSubject struct {
	TeacherID uuid.UUID
	SubjectID uuid.UUID
}

type TeacherWorkload struct {
	WorkloadID          uuid.UUID
	TeacherID           uuid.UUID
	MaxHoursPerWeek     string
	CurrentHoursPerWeek string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
}

type Timetable struct {
	TimetableID  uuid.UUID
	SchoolID     uuid.UUID
	AcademicYear string
	Semester     sql.NullString
	Title        string
	Description  sql.NullString
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type TimetableEntry struct {
	EntryID     uuid.UUID
	TimetableID uuid.UUID
	ClassID     uuid.UUID
	SubjectID   uuid.UUID
	TeacherID   uuid.UUID
	RoomID      uuid.UUID
	DayOfWeek   int32
	StartTime   time.Time
	EndTime     time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Transaction struct {
	TransactionID        uuid.UUID
	InvoiceID            uuid.UUID
	SchoolID             uuid.UUID
	Amount               string
	TransactionDate      time.Time
	PaymentMethod        sql.NullString
	GatewayTransactionID sql.NullString
	Status               string
	Notes                sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Transcript struct {
	TranscriptID   uuid.UUID
	SchoolID       uuid.UUID
	StudentID      uuid.UUID
	AcademicYear   string
	CumulativeGpa  sql.NullString
	TranscriptData json.RawMessage
	IssuedAt       time.Time
	IssuedByUserID uuid.NullUUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type TransferRequest struct {
	TransferID          uuid.UUID
	EntityType          string
	EntityID            uuid.UUID
	SourceSchoolID      uuid.UUID
	DestinationSchoolID uuid.UUID
	InitiatedByUserID   uuid.UUID
	Status              string
	RequestDate         time.Time
	CompletionDate      sql.NullTime
	Notes               sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type TransportAllocation struct {
	AllocationID uuid.UUID
	SchoolID     uuid.UUID
	UserID       uuid.UUID
	RouteID      uuid.UUID
	StopID       uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TransportRoute struct {
	RouteID    uuid.UUID
	SchoolID   uuid.UUID
	VehicleID  uuid.NullUUID
	RouteName  string
	StartPoint sql.NullString
	EndPoint   sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TransportStop struct {
	StopID     uuid.UUID
	RouteID    uuid.UUID
	StopName   string
	PickupTime sql.NullTime
	DropTime   sql.NullTime
	Fare       sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TransportVehicle struct {
	VehicleID     uuid.UUID
	SchoolID      uuid.UUID
	VehicleNumber string
	Capacity      int32
	DriverName    sql.NullString
	DriverPhone   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	UserID            uuid.UUID
	SchoolID          uuid.NullUUID
	RoleID            uuid.UUID
	FirstName         string
	LastName          string
	Email             string
	ContactEmail      sql.NullString
	FirebaseUid       sql.NullString
	PasswordHash      sql.NullString
	PhoneNumber       sql.NullString
	DateOfBirth       sql.NullTime
	Gender            sql.NullString
	ProfilePictureUrl sql.NullString
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         sql.NullTime
	SearchVector      interface{}
}
